site: Made Jekyll Theme

url:
baseurl:

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /project/:slug
  collections_template:
    output: true
    permalink: /collections_template/:slug

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "collections_template"
    values:
      layout: "post"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

sass:
  style: compressed

plugins:
  - jekyll-sitemap
  - jekyll-paginate-v2


pagination:
  collections:
    posts:
      per_page: 7
      permalink: '/blog/page:num/'
      sort_field: 'date'
      sort_reverse: true
      title: 'Collections Template Page :num'
    collections_template:
      per_page: 7
      permalink: '/collections_template/page:num/'
      sort_field: 'date'
      sort_reverse: true
      title: 'Collections Template Page :num'
