site: Made Jekyll Theme

url:
baseurl:

collections:
  pages:
    output: true
    permalink: /:name
  posts:
    output: true
    permalink: /blog/:slug
  projects:
    output: true
    permalink: /project/:slug
  tags:
    output: true
    permalink: /tags/:name

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: ""
      type: "tags"
    values:
      layout: "tag_page"

markdown: kramdown
highlighter: rouge

kramdown:
  input: GFM
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

sass:
  style: compressed

plugins:
  - jekyll-paginate-v2

pagination:
  enabled: true
  per_page: 7
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 2
    after: 2
  collections:
    posts:
      output: true
      permalink: '/blog/page/:num/'
      title_suffix: ' - page :num'
      layout: 'post'
    tags:
      output: true
      permalink: '/tags/:name/:num/'
      title_suffix: ' - page :num'
      layout: 'tag_page'
